apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: beer-rec-pvc
  namespace: beer-rec-system
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
  volumeMode: Filesystem