apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: beer-horoscope-api
  name: beer-horoscope-api
  namespace: beer-rec-system
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: beer-horoscope-api
  strategy: {}
  template:
    metadata:
      labels:
        app: beer-horoscope-api
    spec:
      containers:
      - image: image-registry.openshift-image-registry.svc:5000/beer-rec-system/beer-horoscope-api:latest
        name: beer-horoscope-api
        env:
          - name: TRAINED_MODELS_DIR
            value: "/mnt/storage/out/"
          - name: HOST
            value: "mysql"
          - name: PORT
            value: "3306"
          - name: DATABASE
            value: "beer_horoscope"
          - name: USER
            value: "user"
          - name: PASSWORD
            value: "password"
        volumeMounts:
          - mountPath: "/mnt/storage"
            name: storage
      volumes:
        - name: storage
          persistentVolumeClaim:
            claimName: beer-rec-pvc
---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: beer-horoscope-api
  name: beer-horoscope-api
  namespace: beer-rec-system
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  ports:
  - name: 5000-5000
    port: 5000
    protocol: TCP
    targetPort: 5000
  selector:
    app: beer-horoscope-api
  type: ClusterIP